### ISSUE TITLE
Installer script failing

### ISSUE THREAD

**Issue by jcounts** [evansde77/cirrus#117]
The installer script is currently failing with the following traceback:

```
Traceback (most recent call last):
  File "/Users/jordancounts/.cirrus/venv/bin/selfsetup", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/jordancounts/.cirrus/venv/lib/python2.7/site-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/Users/jordancounts/.cirrus/venv/lib/python2.7/site-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/Users/jordancounts/.cirrus/venv/lib/python2.7/site-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/jordancounts/.cirrus/venv/lib/python2.7/site-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: lazy-object-proxy
```

I've tried upgrading pip and installing `lazy-object-proxy` but still receive the same error. I had cirrus installed before but had removed it because `selfupdate` was not upgrading to latest release. I'm running OS X 10.11.5.

**Comment by evansde77** [comment]
If you blow away the ~/.cirrus dir entirely and reinstall it from scratch
that persists? Which version of python etc?

**Comment by jcounts** [comment]
Yes I removed  ~/.cirrus first

Python 2.7.10

**Comment by evansde77** [comment]
Did you manage to resolve this? I think the root cause is an old setuptools/legacy distribute install in your system/base python, and I can add a check for that in the installer script to make it clear.

**Comment by jcounts** [comment]
Got this working now. I had to update pip, distribute, and setuptools. It seems like the setuptools that exist on the venv are out of date by default. I know you weren't able to reproduce so it's possible something strange happened specific to my machine. I also was seeing the installer script fail when running `selfsetup` so I had to activate the venv and do it myself. Not sure if that is a bug or not. If you cannot reproduce feel free to close this Issue.

**Comment by evansde77** [comment]
You still have distribute installed? I would wipe it out, it got absorbed into setuptools a while back. Ill keep this open and use it to make the installer more robust:
1. Check setuptools is ~modern & print warning
2. Make sure distribute isnt present & print warning 
3. verify that the cirrus alias is valid if it exists in gitconfig so that updates from old to new style installers arent poop
