### ISSUE TITLE
Missing `import os` in plugins/publishers/jenkins.py

### ISSUE THREAD

**Issue by skscharr** [evansde77/cirrus#129]
Error when trying to run `git cirrus docs publish`

```
$ git cirrus docs publish
2016-07-21;INFO;Preparing to upload documentation...
Traceback (most recent call last):
  File "/Users/samscharr/.cirrus/venv/bin/docs", line 11, in <module>
    sys.exit(main())
  File "/Users/samscharr/.cirrus/venv/lib/python2.7/site-packages/cirrus/docs.py", line 58, in main
    publish_documentation(opts)
  File "/Users/samscharr/.cirrus/venv/lib/python2.7/site-packages/cirrus/documentation_utils.py", line 161, in publish_documentation
    plugin.publish(opts, doc_artifact)
  File "/Users/samscharr/.cirrus/venv/lib/python2.7/site-packages/cirrus/plugins/publishers/jenkins.py", line 73, in publish
    filename = os.path.basename(doc_artifact)
NameError: global name 'os' is not defined
```

https://github.com/evansde77/cirrus/blob/develop/src/cirrus/plugins/publishers/jenkins.py

**Comment by skscharr** [comment]
yeah... I'll go through and take care of these, just documenting as I find it...

**Comment by evansde77** [comment]
@skscharr can this be closed out now?
