### ISSUE TITLE
Wrong version of python created

### ISSUE THREAD

**Issue by jordansamuels** [evansde77/cirrus#189]
I discussed this a bit with @evansde77 and showed him some evidence, although we haven't dug all the way into the specific failure causes.  When you specify `python=3.6' or `python=python3.6` in `cirrus.conf` it appears not to be honored (at least in some cases) unless you specify `git cirrus build -p 3.6` rather than just `git cirrus build`.  I'll try to post some more specific failure scenarios.

**Comment by jordansamuels** [comment]
Update: this is user error and not cirrus' fault (although we may want to add a warning).

I didn't realize it, but right in [the documentation for conda](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) it says you can specify the python version in the `environment.yml` file.  Using this method, I have no problems.

Discussed with @evansde77 that maybe a warning is appropriate for when you are using the conda builder and also specify a python version in `cirrus.conf`, since the latter will be ignore.

I'm fine with this issue being closed.  Sorry for my confusion.

**Comment by jordansamuels** [comment]
So actually it's more subtle.  My previous comment is 100% accurate for the `CondaEnv` builder.  However, using the default `VirtualenvPip` builder, this issue does exist - at least using the Conda version of cirrus (which is a system-wide thing, not project-wide thing).  

Steps (after installing conda, and the the [conda cirrus installer](https://raw.githubusercontent.com/evansde77/cirrus/develop/conda-installer.sh
):

```
mkdir tmp; cd tmp; git init;
git cirrus package init --bootstrap -p issue_189  -v 0.0.0 -s src --python 3.6 --no-remote
git cirrus build
venv/bin/python --version
```

This gives 3.5.4. 

The workaround is to re-specify on the command line `git cirrus build -p 3.6`.

**Comment by evansde77** [comment]
Doing some tests for this on an anaconda 4.4.0 docker container:

The default virtualenv pip plugin fails because the python version isnt a valid binary:

```
[root@28243e8442e7 tmp]# git cirrus build -b VirtualenvPip
2017-12-08;INFO;Using builder: VirtualenvPip
2017-12-08;INFO;Bootstrapping virtualenv: /tmp/test/tmp/venv
Traceback (most recent call last):
  File "/root/.cirrus/venv/bin/build", line 11, in <module>
    sys.exit(main())
  File "/root/.cirrus/venv/lib/python3.6/site-packages/cirrus/build.py", line 148, in main
    plugin_build(opts, extras)
  File "/root/.cirrus/venv/lib/python3.6/site-packages/cirrus/build.py", line 138, in plugin_build
    builder.create(**options)
  File "/root/.cirrus/venv/lib/python3.6/site-packages/cirrus/plugins/builders/venv_pip.py", line 55, in create
    venv.open_or_create()
  File "/root/.cirrus/venv/lib/python3.6/site-packages/virtualenvapi/manage.py", line 182, in open_or_create
    self._create()
  File "/root/.cirrus/venv/lib/python3.6/site-packages/virtualenvapi/manage.py", line 105, in _create
    raise VirtualenvCreationException((returncode, output, self.name))
virtualenvapi.exceptions.VirtualenvCreationException: (3, b'The path 3.6 (from --python=3.6) does not exist\n', 'venv')

```

The CondaPip builder seems to work fine and gives you python3.6, but that may be because thats the default python3 on the image...  going to try with an older conda version and 3.5...
