### ISSUE TITLE
package init --register-with-pypi fails

### ISSUE THREAD

**Issue by Maxsparrow** [evansde77/cirrus#211]
Ran:
```
git cirrus package init                     \
--bootstrap                                             \
 -p cjohnson_test_cirrus                              \                
--pypi-package-name cjohnson.test.cirrus                    \                        
 -v 0.0.0                                             \
 -s src                                             \
 -o abc                                             \
 -d "<describe package here>"                        \                     
 --python python3.6                                            \  
--use-pypirc                                          \
--register-with-pypi=pydev
```

Result:
```
...(Good until here)...
2018-11-28;INFO;Registering package /Users/cjohnson/code/test-repo/dist/cjohnson.test.cirrus-0.0.0.tar.gz with pypi pydev
Traceback (most recent call last):
  File "/Users/cjohnson/.cirrus/venv/bin/package", line 11, in <module>
    sys.exit(main())
  File "/Users/cjohnson/.cirrus/venv/lib/python2.7/site-packages/cirrus/package.py", line 930, in main
    init_package(opts)
  File "/Users/cjohnson/.cirrus/venv/lib/python2.7/site-packages/cirrus/package.py", line 874, in init_package
    register_package(package, opts.register_with_pypi)
  File "/Users/cjohnson/.cirrus/venv/lib/python2.7/site-packages/cirrus/twine_helpers.py", line 45, in register_package
    None
TypeError: register() takes exactly 2 arguments (9 given)
```

**Comment by evansde77** [comment]
which version of twine do you have installed?

**Comment by evansde77** [comment]
It appears that the twine API changed, in twine 1.12 so would suggest downgrading that and see if that resolves the issue, ill pin the version more concretely in the cirrus requirements and look at making it compatible with the new code.
