### ISSUE TITLE
Interesting issue when creating feature branch

### ISSUE THREAD

**Issue by jcounts** [evansde77/cirrus#32]
[09:23:02 cirrus](develop) git cirrus feature new pull-request-warning
Traceback (most recent call last):
  File "/Users/jordancounts/.cirrus/cirrus/venv/bin/feature", line 9, in <module>
    load_entry_point('cirrus==0.0.7', 'console_scripts', 'feature')()
  File "/Users/jordancounts/.cirrus/cirrus/src/cirrus/feature.py", line 107, in main
    new_feature_branch(opts)
  File "/Users/jordancounts/.cirrus/cirrus/src/cirrus/feature.py", line 62, in new_feature_branch
    config.gitflow_branch_name())
  File "/Users/jordancounts/.cirrus/cirrus/src/cirrus/git_tools.py", line 34, in checkout_and_pull
    return repo.remotes.origin.pull(ref)
  File "/Users/jordancounts/.cirrus/cirrus/venv/lib/python2.7/site-packages/git/remote.py", line 605, in pull
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/Users/jordancounts/.cirrus/cirrus/venv/lib/python2.7/site-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len(["f810acc83daea86f9410a8b9f8a4762cd10654ba\t\tbranch 'develop' of https://github.com/evansde77/cirrus\n"]) != len(['POST git-upload-pack (976 bytes)', 'POST git-upload-pack (gzip 1426 to 791 bytes)', '   8582a75..f810acc  develop    -> origin/develop'])

Ran the same line again and it worked however.

**Comment by evansde77** [comment]
@jcounts have you seen this again since?

**Comment by jcounts** [comment]
Yea, doesn't happen often. Running the command again is current solution.

**Comment by evansde77** [comment]
Hmmn, wonder if it needs a fetch in there to get the extra tags

**Comment by evansde77** [comment]
Looks like there were some bugs in GitPython that got fixed, will see if an update addresses this
