### ISSUE TITLE
Better handle unknown commands

### ISSUE THREAD

**Issue by evansde77** [evansde77/cirrus#39]
When you are too dumb to type the right commands, the distributor should probably tell you instead of puking:

[13:45:21 carburetor] (develop) git cirrus new feature dynamite-error-handling
Traceback (most recent call last):
  File "/Users/david/.cirrus/cirrus/venv/bin/cirrus", line 9, in <module>
    load_entry_point('cirrus==0.0.7', 'console_scripts', 'cirrus')()
  File "/Users/david/.cirrus/cirrus/src/cirrus/delegate.py", line 86, in main
    exit_code = run_command([command_path, ] + args[1:])
  File "/Users/david/.cirrus/cirrus/src/cirrus/delegate.py", line 38, in run_command
    return subprocess.call(cmd, shell=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by evansde77** [comment]
fixed
