### ISSUE TITLE
Handle None values in commit data from github

### ISSUE THREAD

**Issue by ksnavely** [evansde77/cirrus#40]
While making a release I encountered the following:
```
Traceback (most recent call last):
  File "/Users/Kyle/.cirrus/cirrus/venv/bin/release", line 9, in <module>
    load_entry_point('cirrus==0.0.7', 'console_scripts', 'release')()
  File "/Users/Kyle/.cirrus/cirrus/src/cirrus/release.py", line 325, in main
    new_release(opts)
  File "/Users/Kyle/.cirrus/cirrus/src/cirrus/release.py", line 210, in new_release
    config.release_notes_format()
  File "/Users/Kyle/.cirrus/cirrus/src/cirrus/github_tools.py", line 232, in build_release_notes
    msgs = get_commit_msgs(org, repo, sha)
  File "/Users/Kyle/.cirrus/cirrus/src/cirrus/github_tools.py", line 147, in get_commit_msgs
    "committer" : commit['committer']['login'],
TypeError: 'NoneType' object is not subscriptable
```

This turned out to be because an employee had specified a different email address than normal (a short alias v. long full addy) and the commit ended up not being attached to the committer.

This looks like this in pdb:
```
> /Users/Kyle/.cirrus/cirrus/src/cirrus/github_tools.py(146)get_commit_msgs()
-> result.append({
(Pdb) pp commit
{u'author': None,
 u'comments_url': u'https://api.github.com/repos/cloudant/carburetor/commits/9ceed9da8f6de577c91a9399cfac245d1d98ef96/comments',
 u'commit': {u'author': {u'date': u'2014-10-21T20:10:09Z',
                         u'email': u'...',
                         u'name': u'...'},
             u'comment_count': 0,
             u'committer': {u'date': u'2014-10-21T20:10:09Z',
                            u'email': u'...',
                            u'name': u'...'},
             u'message': u"Secret FooBar.",
             u'tree': {u'sha': u'1f9d1e66dad927393410b88c6be6a8a353f549a4',
                       u'url': u'https://api.github.com/repos/cloudant/carburetor/git/trees/1f9d1e66dad927393410b88c6be6a8a353f549a4'},
             u'url': u'https://api.github.com/repos/cloudant/carburetor/git/commits/9ceed9da8f6de577c91a9399cfac245d1d98ef96'},
 u'committer': None,
 u'html_url': u'https://github.com/cloudant/carburetor/commit/9ceed9da8f6de577c91a9399cfac245d1d98ef96',
 u'parents': [{u'html_url': u'https://github.com/cloudant/carburetor/commit/983002253dc091a08eb29e07b712c41842e8ffda',
               u'sha': u'983002253dc091a08eb29e07b712c41842e8ffda',
               u'url': u'https://api.github.com/repos/cloudant/carburetor/commits/983002253dc091a08eb29e07b712c41842e8ffda'}],
 u'sha': u'9ceed9da8f6de577c91a9399cfac245d1d98ef96',
 u'url': u'https://api.github.com/repos/cloudant/carburetor/commits/9ceed9da8f6de577c91a9399cfac245d1d98ef96'}
```
The None values cause the raise.

**Comment by ksnavely** [comment]
Fixed!
